### ISSUE TITLE
[Bug] Cannot create factory for existing model - `Undefined index: created`

### ISSUE THREAD

**Issue by prodixx** [Laravel-Backpack/devtools-issues#1]
# Bug report

### What I did

I have created several models without factory and seeder.

### What I expected to happen

 After the models were created I've tried to add factory and seeder for those models. 

### What happened

I've got "Undefined index: created" error when trying to generate the factory. Error seems to be on ``` backpack\devtools\src\Generators\BlueprintGenerator.php:516 ```

### What I've already tried to fix it

still investigating at the moment

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.3 (cli) (built: Mar  6 2019 21:53:23) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.3, Copyright (c) 1998-2018 Zend Technologies

### LARAVEL VERSION:
v8.54.0@7b88554cd1aeb52b7f82689bf244182e7a81894b

### BACKPACK VERSION:
4.1.50@09cf360f2c1d1ad40d054c6c36e16c3c44f2e461

**Comment by pxpm** [comment]
Hey @prodixx !

Nice to see you!

Thanks for the feedback, I've just tried it in current master and it worked (atleast with 2 dummy models I've created). 

- please make sure you are running the last devtools version.

If you do, it might be some folder permission issues?

**Comment by prodixx** [comment]
Hey!!

Today I've installed crud and devtools, I'm using v 1.0 . 

I'll try to test more.

Thank you.

**Comment by pxpm** [comment]
It should be 1.0.13 tagged 3 days ago if you just installed today it should be fine, something else is going on :)

I am also working on it, If I can replicate your issue I will let you know here!

Cheers

**Comment by tabacitu** [comment]
Hmmm that's odd... what version of laravel-shift/blueprint do you have installed @prodixx ?

**Comment by prodixx** [comment]
dev-master

**Comment by prodixx** [comment]
I've tried on another computer, with php 7.4. same error. I don't think it's from folder permission because when i generate all files from start, it works. 

I've only tested on windows machine with xamp and laragon. I'll spin a droplet and test on ubuntu, maybe i will find something...

**Comment by pxpm** [comment]
@prodixx I got your error too.

I am on it 👍

**Comment by pxpm** [comment]
I have two setups, one older and a new one I created this morning.

In the older version, when generating the factory, the `$result` variable in line 504 returns: 

![image](https://user-images.githubusercontent.com/7188159/129707279-7be717ee-c51d-4427-8d4d-b1b33c081bcb.png)

While in the new instalation it returns: 

![image](https://user-images.githubusercontent.com/7188159/129707371-801d312c-9b9d-44e7-af12-3d18cbe097d8.png)

**Comment by promatik** [comment]
Hi @prodixx is it possible that you have a non `.php` on models folder?

**Comment by pxpm** [comment]
@promatik I don't think that is the case. There are two different issues, but both started to happen before I ran `composer update` and updated blueprint. 

I could generate factories on an old install, but @prodixx was unable to do it in a new install. When I updated I got the same error and are not able to create factories anymore.

**Comment by promatik** [comment]
@prodixx just to update you on this, a PR to fix this issue is open and will probably be merged soon 🙌

**Comment by promatik** [comment]
Fixed and tagged on v1.0.15 🙌
@prodixx let us know if it solves your issue.

**Comment by tabacitu** [comment]
Also, now we have a public changelog for DevTools - https://backpackforlaravel.com/products/devtools/changelog.md

**Comment by prodixx** [comment]
@promatik yes, all is good now. 

thank you all for a another great product!
