### ISSUE TITLE
[Bug] could not find driver (SQL: create table "models"..) when accessing admin/devtools/model

### ISSUE THREAD

**Issue by gorthal** [Laravel-Backpack/devtools-issues#11]
# Bug report

### What I did

On a new install of backpack and devtools, I can't access to devtools URL because of this error :

`Illuminate\Database\QueryException
could not find driver (SQL: create table "models" ("file" varchar, "id" integer not null primary key autoincrement, "file_type" varchar, "file_extension" varchar, "file_path" varchar, "file_path_absolute" varchar, "file_path_relative" varchar, "file_path_from_base" varchar, "file_name" varchar, "file_name_without_extension" varchar, "file_name_with_extension" varchar, "file_last_accessed_at" datetime, "file_last_changed_at" datetime, "file_last_modified_at" datetime, "file_created_at" datetime, "file_directory" varchar, "file_contents" varchar, "class_name" varchar, "class_namespace" varchar, "class_path" varchar, "class_path_with_extension" varchar, "created_at" datetime, "updated_at" datetime)) `

Database is correctly setup in the .env file.
Query works in the main app code.

### What I've already tried to fix it

I try to reinstall my laravel and packages from scratch with a new Laravel 8 install with no other package or class. It fails again.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### LARAVEL VERSION:
v8.60.0@44f16a31a1d4ac8a51605550d7796e2273984a48

### BACKPACK VERSION:
4.1.52@239e60df0436f8a817facce20a2dffcb2b6e7250

**Comment by tabacitu** [comment]
Sorry for the bad experience @gorthal . That's very odd indeed. From the name of the table (`models`) I'd wager it's about not having SQLite installed, rather than MySQL. Is that possible, that you don't have sqlite on your system? We never considered that might be possible...

1. What happens if you run `sqlite3 --version` in your command line?
2. What's your Operating System (Windows / MacOS / Linux) & its version? 
3. How's your local server set up? Homestead / WAMP / XAMPP / Valet?

**Comment by gorthal** [comment]
Hi @tabacitu !

Oh, I see! It's the first time I use Laragon on Windows for my dev process on Laravel. I did not notice that Sqlite was missing. I gonna install it and give you feedback. Thank you so much for your help.

**Comment by tabacitu** [comment]
I'm not 100% sure that's what's happening, it's just a wild guess. Thank you for the understanding. Let us know, we'll keep this issue open until we're sure you can use DevTools, and what the problem was.

Cheers!

**Comment by gorthal** [comment]
@tabacitu : you're the best ! 
It was precisely the sqlite3 extension that was not loaded in PHP. 
If anyone else using Laragon have the same problem, here's how to activate it:
![image](https://user-images.githubusercontent.com/201709/132821097-bf095fc4-605a-4d5d-b522-3ff2fe7ead86.png)

Thank you for your help @tabacitu , now can I start my new cool project!
Have a great day
Cheers

**Comment by tabacitu** [comment]
Great to hear that! 

@promatik what do you think of adding a check to see if SQLite is installed, at the end of the installation command? And if failing we would show a notice telling the dev to do that?

It should be possible using phpinfo() right? https://www.plus2net.com/php_tutorial/sqlite-support.php
