### ISSUE TITLE
[Feature Request] Postgres Support

### ISSUE THREAD

**Issue by arb362** [Laravel-Backpack/devtools-issues#14]
# Feature Request

### What's the feature you think DevTools should have?

PostgreSQL DB Support

### How often do you see yourself using this feature, if implemented?

I develop all of my applications with a Postgres backed. If this is added then I will be using it every single time. I actually already purchased the software but didn't notice the MySQL requirement as I was looking at the README. As the migration generator is the most exciting thing for me, I would absolutely LOVE IT if this is added.

**Comment by promatik** [comment]
Hi @arb362!
Thank you so much for your feedback, and sorry for the trouble.

I opened a PR for fixing the issues with PostgreSQL, right now I was able to run it with a pgsql database 🙌
We'll now review it and let you know once we merge it ✌

**Comment by arb362** [comment]
That sounds great! Thanks much!

**Comment by tabacitu** [comment]
Hey @arb362 - indeed PostgreSQL wasn't in the first beta, but @promatik 's PR brings support for it now. We've just tagged and released it, please do a `composer update backpack/devtools` to get 1.0.25+ - that should fix it for you.

Let us know if it doesn't, or you get any more PostgreSQL-related errors, and we'll reopen this or quickly squash those too.

Thanks again.
Cheers!
