### ISSUE TITLE
[Bug] failed to open stream: No such file or directory when creating new model

### ISSUE THREAD

**Issue by malle-pietje** [Laravel-Backpack/devtools-issues#17]
# Bug report

### What I did

I initially created a model (Customer) that I wanted to redo using the DevTools  so I deleted all the generated files. I then tried to create a new version of the model.

PS: **it's a pity you cannot modify an existing model using DevTools**

### What I expected to happen

The new model and its files are created.

### What happened

An Exception is thrown:

```
include(/home/erik/laravel/customers/ICT-Web-Solution/admin_gen2/vendor/composer/../../app/Models/Customer.php): failed to open stream: No such file or directory
```

### What I've already tried to fix it

Retried multiple times, restarted web server, changed browser, no idea what else to do.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.9 (cli) (built: Jul  5 2021 13:33:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.67.0@fc52acafd069aedc079bf8f17d1a4af4ef489b1e

### BACKPACK VERSION:
4.1.57@7996979454fb7e02a866ee56dd7569f7d35f5ded

### Operating System and Server Setup

I encountered the problem above on my Ubuntu 20.04 machine, and my web server is set up using the LAMP stack.

**Comment by tabacitu** [comment]
A Delete option should would be useful in this case, I agree. 

Let's do it. I've added issue https://github.com/Laravel-Backpack/DevTools/issues/264 for this.

**Comment by tabacitu** [comment]
I'm going to close this - we've added an issue to create a Delete button, that should make this experience a lot better. If anybody else gets this problem please post your experience here and we'll reopen 🙏

**Comment by AxelGanter** [comment]
same problem here

- I reverted all changes
- I deleted tables in DB
- I deleted last lines in migrations

Return type of Backpack\DevTools\CustomFile::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /home/username/laravelproject/vendor/backpack/devtools/src/CustomFile.php on line 373

**Comment by AxelGanter** [comment]
I quess its some kind of cache somewhere .... ?

test with an incognito browser failed as well
restarting artisan serve did not help

php artisan cache:clear
did also NOT work
