### ISSUE TITLE
[Feature Request] enable `ShowOperation` by default

### ISSUE THREAD

**Issue by Polfo** [Laravel-Backpack/devtools-issues#19]
# Feature Request

### What's the feature you think DevTools should have?

The generated crud does not have a setupShowOperation() method. It should.
If not, like now, only default columns are shown. Standard practice is to add this code 

```
protected function setupShowOperation()
{
    $this->setupListOperation();
}
```

### How often do you see yourself using this feature, if implemented?

Every time I generate a crud.

**Comment by pxpm** [comment]
Hello @Polfo !

Thanks for the suggestion. I think it's reasonable to have a configuration option where developer could choose the default Backpack operations to add. 

@tabacitu What do you think ? We can add a config in file or "checkboxes" in devtools page to select the desired operations.

-Config file:
```php
'default_controller_operations' => ['Backpack/Crud/app/Http/Operations/CreateOperation', 'UpdateOperation']; 
```
PROS
    - Using full namespaces allow developer to add Non-Backpack operations, Devtools would just add the operation trait and create a `setupXXXOperation` function. 

CONS:
    - It would create ALL the operations for ALL cruds, and probably you just want that operation in particular cruds.
    - Not using full namespaces would make it impossible to have default custom operations in your crud panels.

-Checkboxes:
> Display checkboxes with operations next to `Create CRUD Controller` to select what operations dev want to create.

PROS
    - Developer can select different operations for different crud controllers.
CONS
    - Using checkboxes in Devtools page  would not allow for operations outside Backpack. 

I think a combination of both is what provide most flexibility and functionality so:
- Add the operations to the config file with namespaces, allow developer to add their own too.
- use that config file to show operation checkboxes in the devtools page.

NOTE: we should also probably need a "default custom operation setup". Name is long, but it says it all. So when user select `ShowOperation`, by default it would `setupListOperation()`. 

What do you think @tabacitu ?

Pedro

**Comment by Polfo** [comment]
It is confusing to me that currently this code is present in the crud
```
protected function setupUpdateOperation()
{
    $this->setupCreateOperation();
}
```
but not this code 
```
protected function setupShowOperation()
{
    $this->setupListOperation();
}
```

**Comment by Polfo** [comment]
Note: `showOperation` is enabled by default, the generated CRUD contains the line
`use \Backpack\CRUD\app\Http\Controllers\Operations\ShowOperation;`

**Comment by Polfo** [comment]
Note: maybe this feature request should be in the [Laravel-Backpack/CRUD](Laravel-Backpack/CRUD) repository as `php artisan backpack:crud` also has this behaviour.

**Comment by tabacitu** [comment]
Hey @Polfo ,

As far as I know, `ShowOperation` should work fine without fetching the column added in List, so without doing:
```php
protected function setupShowOperation()
{
    $this->setupListOperation();
}
```

Does it not work that way for you?

----

PS. @pxpm I think we have to go a little bit deeper than that. Not only allow devs to choose which operations to enable, but also empower them to define things right then-and-there. So not only checkboxes, but also allow them to check certain features, define fields/columns, etc. I see this as a MAJOR DX improvement for DevTools. But yeah in principle I agree with you about the config + checkbox combo. Config to change the defaults, then checkboxes and inputs as the actual interface.

**Comment by Polfo** [comment]
@tabacitu 
Indeed `ShowOperation` magically works without defining a `setupShowOperation`, but seems to take the configuration from the database and/or the model, I don't know.
It does not take the columns from what I define in `setupListOperation` in a similar way as `setupUpdateOperation` takes the configuration from `setupCreateOperation`
E.g. a `json` field is not displayed.
If I add `CRUD::column('created_at');` to `setupListOperation`, it is not displayed during the `ShowOperation`, which is odd as I would expect more columns displayed in a single record vertical layout than in a table view.

**Comment by tabacitu** [comment]
Ah ok, I understand the confusion here. This is something that annoys me with ShowOperation too - it's not quite intuitive that it will try to "guess" all columns to show. 

I've just changed the docs for 4.2 to make this more clear.
We also have an open PR that makes defining `setupShowOperation()` overwrite all guessing, thereby bringing the behaviour closer to Create & Update (see https://github.com/Laravel-Backpack/CRUD/pull/3132 ). After that PR, if you define:

```php
protected function setupShowOperation()
{
    $this->setupListOperation();
}
```

You will get the exact same thing.

----

However, I do not think that should be the default behaviour. I think the current guessing of all columns is what _most_ developers want, most of the time. So I don't think we'll add the `setupShowOperation()` definition by default when a CrudController is created, sorry.

I might be wrong in my estimate of _what devs want_, of course. If you disagree (and anybody else who stumbles into this), please let us know here and we'll change course. It wouldn't be the first time we're wrong 😅👀😔

Thanks for the idea @Polfo , but I think we'll keep this one as it is. The PR above will help bring the behaviour more in line with your expectations, though.

Cheers!

**Comment by Polfo** [comment]
> I've just changed the docs for 4.2 to make this more clear.
Great.

Well, I often like to have `created_at` and `updated_at` in the showOperation, so I have to add columns manually anyway.

**Comment by tabacitu** [comment]
Hmm... right... that's a good idea... I've added https://github.com/Laravel-Backpack/CRUD/issues/3991 to consider adding `created_at`, `updated_at` and `deleted_at` by default inside the Show operation... that _might_ be useful for most people...

**Comment by Polfo** [comment]
I also like the fake column feature. In that case also, the default behaviour is not enough, but the fake column is defined in the list operation. To me, a show operation is a vertical list operation.
