### ISSUE TITLE
[Bug] request validation rule conflict

### ISSUE THREAD

**Issue by Polfo** [Laravel-Backpack/devtools-issues#27]
# Bug report

### What I did

Generated a model with a fielname that is unique
![image](https://user-images.githubusercontent.com/10303392/144606367-b5775fd5-eb19-4ea8-96f9-91b0fa75faac.png)

### What I expected to happen

    public function rules()
    {
        return [
            'column_name' => 'required|string|unique:table_name,column_name,' . $this->id,
            ...
        ];
    }

### What happened

![image](https://user-images.githubusercontent.com/10303392/144605844-71811363-d993-44f5-9d5a-059171314e36.png)

    public function rules()
    {
        return [
            'column_name' => 'required|string|unique:table_name,column_name',
            ...
        ];
    }

### What I've already tried to fix it

Manually add `,' . $this->id` to the rule

### PHP VERSION:
PHP 8.0.2 (cli) (built: Feb  3 2021 18:36:40) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.74.0@004ea195012d5132eca07a176a6e587c6a74815e

### BACKPACK VERSION:
4.1.61@4400187391eb5b73672c2b166a990cd737277409

### Operating System and Server Setup

I encountered the problem above on my [Windows 10] machine, and my web server is set up using [php artisan serve].

**Comment by tabacitu** [comment]
Yup - I would expect it to have `,' . $this->id` too, if I ticked "unique". 

Any idea why we don't already do this @promatik ?

**Comment by promatik** [comment]
Hi @Polfo! Thank you for this report.

I created a pull request to fix this issue, it should be merged soon ✌

@tabacitu, added an explanation for this on the PR.
