### ISSUE TITLE
[Feature Request] More clarity on Create functions

### ISSUE THREAD

**Issue by Polfo** [Laravel-Backpack/devtools-issues#28]
# Feature Request

### What's the feature you think DevTools should have?

I would like clarification about the difference between `Create Migration` and `Create Model`
They seem very similar to me, why are both present?

I would also like clarification about all the grayed out `Create` functions. They are not active for me. How can they be used? 

![image](https://user-images.githubusercontent.com/10303392/144609651-e8ff693c-ec81-4305-a80f-1f1a6ac71b5d.png)

**Comment by tabacitu** [comment]
Hey @Polfo ,

Both `Migration` and `Model` allow you to create a migration & model. The difference is that in one you define the TABLE NAME (migration), in the other you define the MODEL NAME (model). It's just a different way of looking at things. Some people prefer thinking about it one way, others a different way, but in the end your result is the same.

The greyed out options have not been implemented yet, they're in the works.

Hope it helps.
Cheers!

**Comment by Polfo** [comment]
> The greyed out options have not been implemented yet, they're in the works.
OK, I am not used to this approach. Shouldn't that be marked more explicitely?
