### ISSUE TITLE
[Feature Request] Remember last add Model configuration

### ISSUE THREAD

**Issue by Polfo** [Laravel-Backpack/devtools-issues#29]
# Feature Request

### What's the feature you think DevTools should have?

It would be nice if there was an action that allows to start over a model generation with the parameters previously entered.
The workflow could be to generate a new model, migration and crud using http://127.0.0.1:8000/admin/devtools/model/create, evaluate the results without modifying the code, then compe back to http://127.0.0.1:8000/admin/devtools/model/create or http://127.0.0.1:8000/admin/devtools/model/23/edit and add or modify the previous input. 
This could alse be used to try to reproduce a devtools error.

### How often do you see yourself using this feature, if implemented?

On each crash
On each model generated, I rarely do it completely right the first time.

**Comment by tabacitu** [comment]
Haha we had the exact same thinking process. It's in the works, thanks!

I'll close this issue as we already have a PR for this in the source.

Cheers!
