### ISSUE TITLE
[Feature Request] Make validation rule match field size

### ISSUE THREAD

**Issue by Polfo** [Laravel-Backpack/devtools-issues#31]
# Feature Request

### What's the feature you think DevTools should have?

When I define a string with a certain length
![image](https://user-images.githubusercontent.com/10303392/144674706-c8721525-bcdf-45f7-b477-7530abeee0fe.png)
the corresponding request rule should reflect this 

    return [
        'str10' => 'required|string',
    ];

should be

    return [
        'str10' => 'required|string|max:10',
    ];

If not, I face

```
Illuminate\Database\QueryException
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'str10' at row 1 (SQL: update `table_name` set `str10` = 123456789, `table_name`.`updated_at` = 2021-12-03 21:19:34 where `id` = 2)
```

### How often do you see yourself using this feature, if implemented?

Every time I set the length of a field

**Comment by tabacitu** [comment]
I agree. This is a current limitation of an underlying library (`Blueprint`). We plan to remove Blueprint and code our own implementation - when we do that we'll also add `min` and `max` validation rules based on DB column restrictions 👍

**Comment by promatik** [comment]
Thank you for the report @Polfo!

I've already submitted a PR to fix this issue, it will be available in the next DevTools version 🙌
