### ISSUE TITLE
[Bug] Does not detect generated Factory and Seeder

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/devtools-issues#35]
# Bug report

### What I did

Created a simple "Owner" model, with a "name" column. Checked the checkboxes at the bottom to generate factory & seeder.

### What I expected to happen

Create the factory & seeder AND show them in the sidebar.

### What happened

The factory & seeder were created OK, but they don't show up in the sidebar:

<img width="1236" alt="Screenshot 2022-01-17 at 10 42 03" src="https://user-images.githubusercontent.com/1032474/149736265-07db894f-4344-48fa-a8e1-0be19188294c.png">
<img width="1436" alt="Screenshot 2022-01-17 at 10 42 21" src="https://user-images.githubusercontent.com/1032474/149736269-8598c396-604d-408c-8ef8-6c545de6ce80.png">

### What I've already tried to fix it

Nothing yet.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.4.21 (cli) (built: Jul 12 2021 03:04:54) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v7.4.21, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.79.0@8091f07558ff4a890435ff9d25fa9aca0189ad63

### BACKPACK VERSION:
4.2.x-dev@4b4b08d6d6a18f9613a9dbf7cb22e147248c7f73
```

### Operating System and Server Setup

Mac OS with Valet.

**Comment by pxpm** [comment]
Can't reproduce this @tabacitu 

I see you were in 4.2-x branch, so it migth have been fixed ? If not let me know, I've tested with PHP 8.1, L9 and v5 master.

**Comment by promatik** [comment]
Same here, I can't reproduce, tested by creating a Model and a Migration.

**Comment by maurohmartinez** [comment]
Can't reproduce this one either. Factory & seeder always show in sidebar as expected.

**Comment by tabacitu** [comment]
Mnope... 🤷‍♂️
