### ISSUE TITLE
[Bug] In the request class there is a ref to a non existent class

### ISSUE THREAD

**Issue by realtebo** [Laravel-Backpack/devtools-issues#36]
# Bug report

### What I did

I generated a new Model and the FormRequest

### What I expected to happen

Nothing specific

### What happened

the new generated request file contains this row

    use App\Http\Requests\Request;

This class doesn't exists at all in a fresh new Laravel 8 project

### What I've already tried to fix it

Simply, I deleted the row

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 7.4.25 (cli) (built: Oct 20 2021 09:29:27) ( NTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v8.79.0@8091f07558ff4a890435ff9d25fa9aca0189ad63

### BACKPACK VERSION:
4.1.64@e49566ebd4a55e6849ef7e88822e53195719e2b8
```

### Operating System and Server Setup

Indifferent

**Comment by tabacitu** [comment]
Thank you @realtebo ! Sorry for letting this slip through - we've been swamped with the v5 launch and adding support for Laravel 9. We'll take a look at this shortly and remove it - sounds like an easy one!

Thanks again - cheers!

**Comment by pxpm** [comment]
Thanks @realtebo !

Back on all-round fixing. Thanks for the report 🙏 

I've submitted https://github.com/Laravel-Backpack/Generators/pull/128 to address this! 

Cheers 👍
