### ISSUE TITLE
DevTools & Laravel 9.x

### ISSUE THREAD

**Issue by blondie63** [Laravel-Backpack/devtools-issues#37]
What about a new version for your last BackPack ??

**Comment by tabacitu** [comment]
Laravel 9 support is coming! Just 14h ago did our main dependency (laravel-blueprint) push a change we needed - we're now working to add L9 support, so it will most likely be done by the end of the day 🎉

**Comment by tabacitu** [comment]
Update: Blueprint added L9 support 12h ago, BUT... the L9 support they provided was NOT tagged yet. Looks like we'll have to wait a little bit more, until they release their L9 support.

PS. Internal link where we provide L9 support to DevTools - https://github.com/Laravel-Backpack/DevTools/pull/271

**Comment by tabacitu** [comment]
I have great news! [Blueprint just launched L9 support](https://github.com/laravel-shift/blueprint/releases/tag/v2.3.0), so now DevTools can have L9 support too. I've just pushed version 1.0.30 which makes it work on Laravel 9 🎉🎉🎉

**Comment by blondie63** [comment]
Very good!!

Thanks

I've some issue converting my project to backpack 5 , i've to try again

**Comment by blondie63** [comment]
How is situations about https://backpackforlaravel.com/docs/5.x/add-ons-official ?
Just all ready for BackPack 5 & LV 9 ?

**Comment by tabacitu** [comment]
Yes, all of them there support Backpack v5 and Laravel  9. However, there are still two first-party addons that DO NOT yet support Laravel 9:
- https://github.com/laravel-backpack/filemanager
- https://github.com/laravel-backpack/langfilemanager

They're not featured in the page you mentioned. But they do exist. And they don't support L9 yet.

**Comment by blondie63** [comment]
Thanks
