### ISSUE TITLE
[Bug] There are no commands defined in the "backpack:devtools" namespace.

### ISSUE THREAD

**Issue by de-raaf-media** [Laravel-Backpack/devtools-issues#4]
# Bug report

### What I did

added a repository to composer.json
composer require --dev backpack/devtools (success)
executed php artisan backpack:devtools:install

### What I expected to happen

Devtools to be installed automatically 

### What happened

There are no commands defined in the "backpack:devtools" namespace.

  Did you mean one of these?
      backpack
      backpack:filemanager

### What I've already tried to fix it

Following every step in installation again

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.4.18 (cli) (built: May  3 2021 11:27:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.18, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.49.0@855a919d08b45f93cb3cf709736528c3d1531884

### BACKPACK VERSION:
4.1.48@53bc6028f445f9b2ecfb8893283f6b6087539353

**Comment by tabacitu** [comment]
Hi @de-raaf-media , 

That command was added a few weeks ago, I think you've installed an earlier version of devtools that doesn't have it... Can you please run `composer require --dev --with-all-dependencies backpack/devtools` or a `composer update`? 

Then you should be able to run `php artisan backpack:devtools:install`.

Let us know.
Cheers!

**Comment by de-raaf-media** [comment]
- Upgrading backpack/devtools (1.0.7 => 1.0.21)

Fixed! Thanks.
