### ISSUE TITLE
[Bug] Cannot create model using Json Column Type

### ISSUE THREAD

**Issue by AlienHack** [Laravel-Backpack/devtools-issues#40]
# Bug report

### What I did

Create new model that contains json column type

### What I expected to happen

Model created with repeatable field successfully

### What happened

Crashed with `Undefined array key "args"`

### What I've already tried to fix it

-

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.1.3 (cli) (built: Feb 16 2022 08:26:12) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.3, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.4.1@29f0aaade82eadd20ef881b4efb88b0dad4e9a5b

### BACKPACK VERSION:
5.0.10@f0c0c45914c39a9083e19f0c5c3d10ef0e142565
```

### Operating System and Server Setup

I encountered the problem above on my [Windows 10] machine, and my web server is set up using [laragon].

**Comment by pxpm** [comment]
This is exactly the same issue as #41 . Please see [this comment](https://github.com/Laravel-Backpack/devtools-issues/issues/41#issuecomment-1063922408) .

Going to close this one! Cheers and thanks @AlienHack
