### ISSUE TITLE
[Bug] Cannot create model using Text Column Type

### ISSUE THREAD

**Issue by AlienHack** [Laravel-Backpack/devtools-issues#41]
# Bug report

### What I did

Create new model that contains Text column type

### What I expected to happen

Model created with text field successfully

### What happened

Crashed with `Undefined array key "args"`

### What I've already tried to fix it

-

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
PHP 8.1.3 (cli) (built: Feb 16 2022 08:26:12) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.3, Copyright (c) Zend Technologies

### LARAVEL VERSION:
v9.4.1@29f0aaade82eadd20ef881b4efb88b0dad4e9a5b

### BACKPACK VERSION:
5.0.10@f0c0c45914c39a9083e19f0c5c3d10ef0e142565
```

### Operating System and Server Setup

I encountered the problem above on my [Windows 10] machine, and my web server is set up using [laragon].

**Comment by tabacitu** [comment]
Hey @AlienHack ,

Can you please send a screenshot of the error, so we understand WHERE that error came from? Or a link from Ignition?

Cheers!

**Comment by AlienHack** [comment]
Sure !

Here is the Ignition link when creating model using Json column
https://flareapp.io/share/W7zgVak5#F62

and this is for Text column
https://flareapp.io/share/pPvYXAom#F62

@tabacitu 

Thanks!

**Comment by AlienHack** [comment]
> Hey @AlienHack ,
> 
> Sorry to hear you're having trouble using DevTools. Can you please send a screenshot of the error, so we understand WHERE that error came from? Or a link from Ignition?
> 
> Cheers!

@tabacitu It seems to be Json and Text column does not hold key 'args' when creating model.

**Comment by pxpm** [comment]
Hello @AlienHack thanks for the report.

I was 100% sure that I fixed it, and indeed I fixed it!

You can now read on line 215: (notice the check for presence with null-coalescing operator `??`)
https://github.com/Laravel-Backpack/DevTools/blob/0dbca0e86a3a70c166cf7f5d28fb7a07807f5070/src/Generators/BlueprintGenerator.php#L214

Problem is that @tabacitu didn't tag this version yet. Can you please do it @tabacitu ?

**Comment by tabacitu** [comment]
Tagged & released. A `composer update backpack/devtools` should do it for you @AlienHack . Sorry for the bad experience 🙏

**Comment by tabacitu** [comment]
(let us know if it still doesn't work for you)
