### ISSUE TITLE
[Bug] Could not find driver

### ISSUE THREAD

**Issue by newtec-foggia** [Laravel-Backpack/devtools-issues#47]
Hi,

error after installing on a linux machine with ubuntu Ubuntu 20.04.4 LTS :

PHP 8.1.9
sqlite3 --version
3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837balt1

https://flareapp.io/share/q5YMw2D5#F66

Thanks,

**Comment by pxpm** [comment]
Hello @newtec-foggia 

That issue is because of SQLite. You need to install SQLite extension and enable it in your PHP .ini configuration.

Please re-open if you think I am wrong, sometimes I am 🙃 

Cheers

**Comment by newtec-foggia** [comment]
Hello @pxpm 

it was the first thing I checked .. (extension=pdo_sqlite is enabled)

[php-ini.pdf](https://github.com/Laravel-Backpack/devtools-issues/files/9393073/php-ini.pdf)

**Comment by pxpm** [comment]
Hello @newtec-foggia 

The fact that the driver is installed for "console" does not mean that the "webserver" has access to that driver, depending on your installation the console php may be different from browser php. 

Can you `dd(php_info())` and check if extension is there in browser ? 

Cheers

**Comment by newtec-foggia** [comment]
Hello @pxpm 

[PHP 8.1.9 - phpinfo().pdf](https://github.com/Laravel-Backpack/devtools-issues/files/9395144/PHP.8.1.9.-.phpinfo.pdf)
[php-ini.pdf](https://github.com/Laravel-Backpack/devtools-issues/files/9395145/php-ini.pdf)

**Comment by newtec-foggia** [comment]
Hello @pxpm 

i installed sqlite again (sudo apt-get install php-sqlite3), now it works.
Thank you

**Comment by pxpm** [comment]
Hello @newtec-foggia I am sorry but I don't feel safe opening pdfs from unknow sources and I am not willing to spin a VM for it, can  you just copy paste from the browser and paste it here ? 

Cheers

**Comment by pxpm** [comment]
Ohh nice, forgot about what I said then!

Happy it's working, if you find something broken please let us know 👍 

Cheers

**Comment by evarioooo** [comment]
Unknow sources from github? lul .. please close this

**Comment by pxpm** [comment]
> Unknow sources from github? lul .. please close this

Clearly you are the one to lul from if you keep opening pdfs from unknown sources. Good luck mate 👍
