### ISSUE TITLE
[Bug] `str_repeat` can't have `0` as input

### ISSUE THREAD

**Issue by pxpm** [Laravel-Backpack/devtools-issues#50]
We got an error report about some `str_repeat` error. https://stackoverflow.com/questions/73435821/laravel-backpack-devtools-add-on-not-working

Discussing a previous issue with @promatik we came to the conclusion that in some scenarios it's possible that `str_repeat` got `0` as input and raised the error.

This is somewhat related to the new output for commands, so @promatik is the best fit here.

**Comment by rhdevelopmentorg** [comment]
Do you have an idea of when this will be patched? I bought devtools to build the cruds for me. If it doesn't do this and doesn't let me admin the cruds, it pretty pointless.

Also, I noticed the last 3 "bug" tagged issues are loosely about the same issue, yet the first is 17 days old. As a paid product I would think the patches would take priority over the free product, no?

**Comment by pxpm** [comment]
Hello @rhdevelopmentorg , sorry for the bad experience. I expect this to be patched in the next days. @promatik is already aware of the issue.

Devtools is a difficult package to debug as it works very coupled with operative system/packages. 
We are even building something to help us to debug devtools issues. 
I was not able to reproduce the user issue regarding str_repeat, I just know that in some environment it could happen again.
Usually "breaking code" is fixed way quicker, especially when we could reproduce the issue, that's not the case here.
I don't have enough fingers to count the times some error was reported and the solution was "obvious" and in the end if we did something about it we would make things worst. 
That's why we have the golden rule of "reproduce the issue before fixing it". 
In devtools that complexity is exponentially bigger for all the reasons I've already pointed out. 

Once again, sorry for the bad experience, I will be monitoring this issue a nudging @promatik to fix it :)

Let me know if there's something I can do to help more here. 

Cheers

**Comment by rhdevelopmentorg** [comment]
Not sure if it helps but attached is the stack trace. Looks like it's the 'progressBlock' function in the 'PrettyCommandOutput' trait.
[stack.txt](https://github.com/Laravel-Backpack/devtools-issues/files/9397620/stack.txt)

**Comment by pxpm** [comment]
That is wayyyyy wayyyyy more helpful than the issue description. 

Thanks again 🙏

Ping @promatik

**Comment by tabacitu** [comment]
Hey guys - apparently it was due to a bug we introduced in CRUD. I've just pushed a hotfix, so a `composer update backpack/crud` should get you [5.3.5](https://github.com/Laravel-Backpack/CRUD/releases/tag/5.3.5) where it's fixed. 

It's a weird one, because we couldn't reproduce it on Windows, but I could reproduce it on MacOS. Pfiew - glad this one is done. Thanks for reporting this @rhdevelopmentorg .

Cheers!

PS. If anybody else is getting this, please run a `composer update`. If you're still seeing the error, then please let us know and we'll reopen.
