### ISSUE TITLE
[Bug] file_put_contents(.blueprint): Failed to open stream: Permission denied

### ISSUE THREAD

**Issue by newtec-foggia** [Laravel-Backpack/devtools-issues#51]
Hi,

after creating a model in an attempt to save this error is reported ..

https://flareapp.io/share/W7zWaKp5#F78

**Comment by pxpm** [comment]
Hello,
You should allow read/write permissions to that folder. .blueprint is a "cache" file for what you create in devtools. 

I don't know what SO you are using, but a Google question should get you going. 

Let me know how it goes. 

Cheers

**Comment by newtec-foggia** [comment]
Hi,

write permissions read / write set but the error does not change (So : Ubuntu)
![status](https://user-images.githubusercontent.com/83398776/186518594-ff9500a2-35e0-4215-b60f-2f08ba3d8df3.JPG)

**Comment by pxpm** [comment]
Something must still be missing, permission issues is not something we can fix on Backpack side. 

Can you check what user is the propertary of that file? Is that the same user where the webserver is run? 
Cheers

**Comment by newtec-foggia** [comment]
Sorry, 
the documentation does not mention any particular permissions necessary for the operation .. which is why I cannot know specifically the folder and its permissions, in any case on the test machine I have no additional user configured but I am working as root user without limitations

**Comment by pxpm** [comment]
Hello @newtec-foggia I never had to give any specific permissions, and I never had a report about such issue.
I am just following the error message you posted. 

Are you using ftp/sftp to upload your files ? Have the chance to pull them from a git repository ? It migth be something to do with how/when files are created and then uploaded ... not sure, just a guess. 

Are you using Backpack/Generators https://github.com/Laravel-Backpack/Generators ? Can you create something with the generators, like `php artisan backpack:model SomeTestModel` ?

Cheers

**Comment by tabacitu** [comment]
This is very weird @newtec-foggia . DevTools working is very dependant on the localhost setup. It's possible we haven't tested with your exact setup.

So in addition to what Pedro is saying, could you please let us know what software you've installed to serve Laravel websites on localhost?

Thanks a lot!

PS. It's very unusual for DevTools not to work. If you can't get it working, of course, happy to refund - just email us.

**Comment by newtec-foggia** [comment]
Hello @pxpm the error is reported to me when I try to create a model with DevTools (previously installed on the server)

I use local Visual Studio Code and connect via ssh to the remote server using the Terminal

Backpack/Generators (like php artisan backpack:model SomeTestModel) works regularly ..

I cannot complete the creation of the model through DevTools because it reports the error

Thanks,

**Comment by pxpm** [comment]
I am sorry, I think there is not much us Backpack can do here, and since have been some months I am closing this. 

Hope by now you worked out the solution 🙏 

Cheers
