### ISSUE TITLE
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 near "(": syntax error

### ISSUE THREAD

**Issue by maverjk** [Laravel-Backpack/devtools-issues#54]
# Bug report
"DevTools -> Add model" give following error:

> Doctrine\DBAL\Exception\SyntaxErrorException
> An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 near "(": syntax error

### What I did
I did a fresh new installation of Laravel and Backpack. 
Following I reported the versions list:  

> [public_html]$  php artisan backpack:version
> ### PHP VERSION:
> PHP 7.4.32 (cli) (built: Sep 28 2022 09:09:55) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies
>     with Zend OPcache v7.4.32, Copyright (c), by Zend Technologies
>     with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
> 
> ### LARAVEL VERSION:
> v8.83.25@.............
> 
> ### BACKPACK VERSION:
> 5.3.13@............
> 
> [public_html]$ sqlite3 --version
> 3.7.17 2013-05-20 00:56:22 .................

By the way before of "Laravel 8" with Backpack I tried to install "Laravel 9" too and for some reason I got same error.
My server is running Centos 7 with MariaDB 10.5.17. I checked out also phpinfo() if the error could be related to SQLite but it's correctly installed and enabled. 

To be honest I don't know what else to look at or to do.
 
Can someone please help me?

**Comment by maverjk** [comment]
Hello Pedro

Thanks for your interest in it :)

Unfortunately this issue happens always. 
Here, there is the full stack error: [https://flareapp.io/share/dmk1NLV7#F66](url)
While the `composer.lock` content should be that:

>         {
>             "name": "doctrine/dbal",
>             "version": "3.4.5",
>             "source": {
>                 "type": "git",
>                 "url": "https://github.com/doctrine/dbal.git",
>                 "reference": "a5a58773109c0abb13e658c8ccd92aeec8d07f9e"
>             },
>             "dist": {
>                 "type": "zip",
>                 "url": "https://api.github.com/repos/doctrine/dbal/zipball/a5a58773109c0abb13e658c8ccd92aeec8d07f9e",
>                 "reference": "a5a58773109c0abb13e658c8ccd92aeec8d07f9e",
>                 "shasum": ""
>             },

If your need any other code reference please let me know.

Thanks again :)

**Comment by pxpm** [comment]
@maverjk thanks for comming back. 

I am still unable to reproduce your issue. 

Can you go to `vendor/doctrine/dbal/src/Connection.php` around line 1034 when it throws the exception, and do a `dd($e, $sql)` and post the results ? 

It seems something is missing on your installation, `pdo_sqlite` enabled ?

Cheers

**Comment by pxpm** [comment]
Thanks for the feedback @maverjk 

I've just spin up a new sqlite database and run the query you provided me, and no errors returned, just the expected results.

![image](https://user-images.githubusercontent.com/7188159/195323215-306b45f0-eb1d-4224-8954-a45124ae38b5.png)

On your sql query dump, can you also show me the bindings? Your SQL reads `t.name = ? (this is the binding)`, I replaced it with `test` as you can see from the screenshot, but maybe it's the name you are providing in that binding that's breaking it ? 

It's also worth note that I am using `3.36.0` as SQLite driver, while you are using `3.7`, not sure if the problem could be there too. 

Cheers

**Comment by maverjk** [comment]
Hi Pedro

I did some test to understand how to show you the bindings:

>        ...
>         try {
>             if (count($params) > 0) {
>                 if ($this->needsArrayParameterConversion($params, $types)) {
>                     [$sql, $params, $types] = $this->expandArrayParameters($sql, $params, $types);
>                 }
>                 dd($sql, $params);   
>                 $stmt = $connection->prepare($sql);
>                 
>                 $this->bindParameters($stmt, $params, $types);
> 
>                 $result = $stmt->execute();
>             } else {
>                 $result = $connection->query($sql);
>             }
> 
>             return new Result($result, $this);
>         } catch (Driver\Exception $e) {
>             throw $this->convertExceptionDuringQuery($e, $sql, $params, $types);
>         } finally {
>             if ($logger !== null) {
>                 $logger->stopQuery();
>             }
>         }
> 

This is the result:

> """
>             SELECT t.name AS table_name,
>                    c.*
>               FROM sqlite_master t
>               JOIN pragma_table_info(t.name) c WHERE t.type = 'table' AND t.name NOT IN ('geometry_columns', 'spatial_ref_sys', 'sqlite_sequence') AND t.name = ? ORDER BY t.name, c.cid ◀
> """
> array:1 [▼
>   0 => "models"
> ]

Placing ` dd($sql, $params); ` before of `$stmt = $connection->prepare($sql);` I got no error, but placing it after I got error.
So basically error for some reason is triggered from  ` $stmt = $connection->prepare($sql);`

I don't know how to get `t.name` value, `$sql` has just the reported value when I click on "DevTools -> Add model".
I don't know if it's correct or less as well as I don't know if there should be an expected value.
Speaking about DevTools, during its installation, I just followed some kind of wizard in terminal. I haven't setup any kind of setting regards SQLite or specifically about DevTools.

I did a fresh installation before with PHP 8.1 and L9 but I got same problems, so I rolled back to PHP 7.4 and L8 with versions showed in my first post.

**Comment by maverjk** [comment]
Hi Pedro

I did some test to understand how to show you the bindings:

>        ...
>         try {
>             if (count($params) > 0) {
>                 if ($this->needsArrayParameterConversion($params, $types)) {
>                     [$sql, $params, $types] = $this->expandArrayParameters($sql, $params, $types);
>                 }
>                 dd($sql, $params);   
>                 $stmt = $connection->prepare($sql);
>                 
>                 $this->bindParameters($stmt, $params, $types);
> 
>                 $result = $stmt->execute();
>             } else {
>                 $result = $connection->query($sql);
>             }
> 
>             return new Result($result, $this);
>         } catch (Driver\Exception $e) {
>             throw $this->convertExceptionDuringQuery($e, $sql, $params, $types);
>         } finally {
>             if ($logger !== null) {
>                 $logger->stopQuery();
>             }
>         }
> 

This is the result:

> """
>             SELECT t.name AS table_name,
>                    c.*
>               FROM sqlite_master t
>               JOIN pragma_table_info(t.name) c WHERE t.type = 'table' AND t.name NOT IN ('geometry_columns', 'spatial_ref_sys', 'sqlite_sequence') AND t.name = ? ORDER BY t.name, c.cid ◀
> """
> array:1 [▼
>   0 => "models"
> ]

Placing ` dd($sql, $params); ` before of `$stmt = $connection->prepare($sql);` I got no error, but placing it after I got error.
So basically error for some reason is triggered from  ` $stmt = $connection->prepare($sql);`

I don't know how to get `t.name` value, `$sql` has just the reported value when I click on "DevTools -> Add model".
I don't know if it's correct or less as well as I don't know if there should be an expected value.
Speaking about it during installation of DevTools I just followed terminal instructions. I haven't setup any kind of setting regards SQLite or specifically about

**Comment by maverjk** [comment]
I don't know if it can help however in `/vendor/doctrine/dbal/src/Schema/SqliteSchemaManager.php`:

(line 697)
>     protected function selectTableColumns(string $databaseName, ?string $tableName = null): Result
>     {
>         $sql = <<<'SQL'
>             SELECT t.name AS table_name,
>                    c.*
>               FROM sqlite_master t
>               JOIN pragma_table_info(t.name) c
> SQL;
> 
>         $conditions = [
>             "t.type = 'table'",
>             "t.name NOT IN ('geometry_columns', 'spatial_ref_sys', 'sqlite_sequence')",
>         ];
>         $params     = [];
> 
>         if ($tableName !== null) {
>             $conditions[] = 't.name = ?';                     <------------------ here we have our  't.name = ?';
>             $params[]     = str_replace('.', '__', $tableName);
>         }
> 
>         $sql .= ' WHERE ' . implode(' AND ', $conditions) . ' ORDER BY t.name, c.cid';
>         
>         dd($sql, $params, $tableName);
> 
>         return $this->_conn->executeQuery($sql, $params);
>     }

` dd($sql, $params, $tableName) ` result:

> """
>             SELECT t.name AS table_name,
>                    c.*
>               FROM sqlite_master t
>               JOIN pragma_table_info(t.name) c WHERE t.type = 'table' AND t.name NOT IN ('geometry_columns', 'spatial_ref_sys', 'sqlite_sequence') AND t.name = ? ORDER BY t.name, c.cid ◀
> """
> array:1 [▼
>   0 => "models"
> ]
> "models"
> 

so `$tableName ` should be `models` ?

**Comment by maverjk** [comment]
Pedro could you please post here result of following `dd($sql, $params, $types, $qcp);` in `/vendor/doctrine/dbal/src/Connection.php` from your fresh installation:

>         try {
>             if (count($params) > 0) {
>                 if ($this->needsArrayParameterConversion($params, $types)) {
>                     [$sql, $params, $types] = $this->expandArrayParameters($sql, $params, $types);
>                 }
>                 dd($sql, $params, $types, $qcp);    <---------------------------------------
>                 $stmt = $connection->prepare($sql);
>                 
>                 $this->bindParameters($stmt, $params, $types);
> 
>                 $result = $stmt->execute();
>             } else {
>                 $result = $connection->query($sql);
>             }
> 
>             return new Result($result, $this);
>         } catch (Driver\Exception $e) {
>             throw $this->convertExceptionDuringQuery($e, $sql, $params, $types);
>         } finally {
>             if ($logger !== null) {
>                 $logger->stopQuery();
>             }
>         }
>     }

**Comment by maverjk** [comment]
Hello

Any news to sort out this issue?

**Comment by maverjk** [comment]
Good morning @pxpm 

Thanks for your reply.
From what I can see, basically we got same results. 
Problem should be related to something else so?

**Comment by pxpm** [comment]
Hey @maverjk 

I am not sure about the usefullness of that, I think we would only find that is some PHP/Database/OS configuration issue or some mismatch configuration between versions, as it seems that the produced SQL is right and it breaks on the `prepare` for pdo. 

What's your `dd($connection)` result ? Here's mine:
![image](https://user-images.githubusercontent.com/7188159/195847542-6d0ee1a9-c6c8-489e-a8fd-305acd01017d.png)

Cheers

**Comment by maverjk** [comment]
`dd($connection)`

> Illuminate\Database\PDO\Connection {#1527 ▼
>   #connection: PDO {#1545 ▼
>     inTransaction: false
>     attributes: {▼
>       CASE: NATURAL
>       ERRMODE: EXCEPTION
>       PERSISTENT: false
>       DRIVER_NAME: "sqlite"
>       ORACLE_NULLS: NATURAL
>       CLIENT_VERSION: "3.7.17"
>       SERVER_VERSION: "3.7.17"
>       STATEMENT_CLASS: array:1 [▼
>         0 => "PDOStatement"
>       ]
>       DEFAULT_FETCH_MODE: BOTH
>     }
>   }
> }

**Comment by tabacitu** [comment]
Thanks for getting so deep into debugging this @maverjk . I'll let you guys continue the conversation. 

Just wanted to say this: No matter if you guys manage to get to the bottom of this or not, our software hasn't behaved as promised to you, and we have to make up for that 🙏 Please email me (cristian.tabacitu@backpackforlaravel.com), I want to give you a refund/discount for the next purchase.

**Comment by maverjk** [comment]
So far so good, it has been really challenging, but I got a way to upgrade SQLite to version "3.39.4". 
The upgrade process on Centos 7 needs a full recompile of "SQLite" and "SQLite shared library" and an update of "PHP-PDO" drivers too. That's because default version on Centos 7 is "3.7.17" and this version does not accept the json extension.
Moreover, as someone mention [here  ](https://forums.cpanel.net/threads/i-need-the-latest-version-of-sqlite3-on-php-7-3.667793/)
> ...
> as with current sqlite version are 3.39.3 and many other package using newer syntax
> with 3.7.17 it will break with newer library such as doctrine/dbal v3 because generated SQL syntax is not support at 3.7.17
> ...

So now "DevTools -> Add model" finally works!

To avoid that someone else would fall in same problems I would suggest to integrate installation prerequisite with a minimum version number for SQLite and SQLite shared Library as well as report them in documentation too.
