### ISSUE TITLE
[Bug] Undefined variable $redirectUrl

### ISSUE THREAD

**Issue by mfaoficial** [Laravel-Backpack/devtools-issues#63]
# Bug report

### What I did

I've tried to create a new Model with factories and all things.

### What I expected to happen

Create the Model, Migrations, etc and back to Models.

### What happened

[Link of the report from laravel](https://pastebin.com/f8pbcXTS)

### What I've already tried to fix it

Nothing yet, i dont have experience in devtools or backpack

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 8.1.9 (cli) (built: Aug  2 2022 14:17:33) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies
    with Xdebug v3.2.1, Copyright (c) 2002-2023, by Derick Rethans

### LARAVEL VERSION:
v10.4.1@7d15f7eef442633cff108f83d9fe43d8c3b8b76f

### BACKPACK PACKAGE VERSIONS:
backpack/crud: 5.5.2
backpack/devtools: 1.3.5
backpack/generators: 3.3.16
backpack/logmanager: v4.0.9
backpack/newscrud: 4.0.9
backpack/permissionmanager: 6.0.16
backpack/pro: 1.6.3
backpack/settings: 3.0.16

### Operating System and Server Setup

I encountered the problem above on my Windows 11 machine, and my web server is set up using Laragon with nginx.

**Comment by phpfour** [comment]
Hello @mfaoficial,

I have tried to reproduce the issue by creating a new Laravel project with the above Backpack packages. I did not encounter any issues as you'll see in this video: https://share.cleanshot.com/wMR4y1WC

Can you share a video like this to help me identify if something is different on your end?

Thanks!
