### ISSUE TITLE
Error on loading dev-tools

### ISSUE THREAD

**Issue by de-raaf-media** [Laravel-Backpack/devtools-issues#7]
# Bug report

### What I did

In admin click de DevTools link

### What I expected to happen

Devtools opening

### What happened

Red notification in top right corder: "Error loading page: Please refresh the page."

**If you need the whole stack let me know**
"message": "syntax error, unexpected 'public' (T_PUBLIC), expecting ';' or ',' (View: /home/vagrant/code/[MYPROJECT]/vendor/backpack/crud/src/resources/views/crud/columns/check.blade.php)",
    "exception": "Facade\\Ignition\\Exceptions\\ViewException",
    "file": "/home/vagrant/code/[MyProject]/database/factories/CategoryFactory.php",
    "line": 22,
    "trace": [

### What I've already tried to fix it

Use the installer (did not work the first time. I thought It was related to that).

**Comment by tabacitu** [comment]
Hi @de-raaf-media - yes can you please give us the whole stack? Or the Flare link to the error? I can't really tell what happened there...

1. What did you do before this happened? 
2. You tried to install DevTools using the installer and it didn't work... how? What error did it give you?

Thanks and sorry for the bad experience. We're still figuring out how DevTools behaves on different combinations of OS, server software, server type, server version, PHP version, MySQL version... there are A LOT of combinations.

**Comment by promatik** [comment]
Hi @de-raaf-media, it seems that you had a missing `;` in a file, can you please check it; ```/home/vagrant/code/[MyProject]/database/factories/CategoryFactory.php:22```

Was it generated by DevTools or was it already present in your project?

**Comment by de-raaf-media** [comment]
My bad! There was indeed a missing ;

Thanks @promatik
