### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Scout3030** [Laravel-Backpack/devtools-issues#70]
# Bug report

### What I did

Running php artisan backpack:require:devtools on a fresh laravel 10.10 setup

### What I expected to happen

Install the dependency

### What happened

An error on console appeared

### What I've already tried to fix it

??

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

````
### PHP VERSION:
PHP 8.1.25 (cli) (built: Oct 27 2023 14:00:40) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.25, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.25, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
10.48.2.0

### BACKPACK PACKAGE VERSIONS:
backpack/basset: 1.3.0
backpack/crud: 6.6.6
backpack/generators: v4.0.4
backpack/permissionmanager: 7.1.1
backpack/theme-tabler: 1.2.8
````

### Operating System and Server Setup

I encountered the problem above on my Linux machine Ubuntu 22.04, and my web server is set up using Valet linux plus.

![2024-03-15_12-15](https://github.com/Laravel-Backpack/devtools-issues/assets/67556814/fd5b1ef0-81e9-4a19-8534-17634bff53c8)

**Comment by jcastroa87** [comment]
Hello @Scout3030 

Did you set your token and Backpack private repository as instructions say on https://backpackforlaravel.com/user/tokens ?

Because Devtools is a paid Addons so, need to set the premium tokens before.

Then check in composer.json is set like this, because you have Backpack 6 and is look like you tried to install Devtools 1.3:
```
"require-dev": {
        "backpack/devtools": "^3.0",
       ...
```

Cheers.

**Comment by pxpm** [comment]
Just to add on @jcastroa87 response, it's possible that you don't have access to a devtools version after ^1.3, you can check in your account tokens if that is the case.

In case it does, there are three solutions for it:
- buy devtools to get the current version you can use with backpack ^6.0
- downgrade to backpack ^5.0 in your project composer.json to use devtools 1.3
- don't use devtools in that project to continue using backpack ^6.0

Cheers

**Comment by jcastroa87** [comment]
Im glad you solve the problem. I will close the issue, but please feel free to re-open or create a new one.

Cheers.
