### ISSUE TITLE
After install: Target class [App\Http\Middleware\CheckIfAdmin] does not exist

### ISSUE THREAD

**Issue by OccultScientist** [Laravel-Backpack/devtools-issues#9]
Installed Laravel (v8.6.1) with homestead and installed dev-tools with:

```
composer require --dev --with-all-dependencies backpack/devtools
php artisan backpack:devtools:install
```

On browsing to http://homestead.test/admin/devtools I see the following error:

Target class [App\Http\Middleware\CheckIfAdmin] does not exist

Extra info:

### PHP VERSION:
PHP 7.4.5 (cli) (built: Apr 19 2020 07:36:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies

### LARAVEL VERSION:
v8.58.0@1b819bf99d87bd543a4d4895e5b3350f61ea7a23

### BACKPACK VERSION:
4.1.51@756173cf6593c3d530fca0e54831763c796e24d8

**Comment by OccultScientist** [comment]
Fixed by installing the full Backpack.
I was initially confused from the docs as documentation said the eloquent models should be in place before full backpack install.

**Comment by tabacitu** [comment]
Great, thanks for the update @OccultScientist . It might be a bit confusing as of now, I admit. I've added docs to the README to mention Backpack should already be installed.

Hopefully https://github.com/Laravel-Backpack/CRUD/pull/3813 will also help in this respect - basically when you run the Backpack installation it will ask you if you want DevTools too.

But we'll consider doing the opposite too - checking if Backpack is already installed and if not, show a pretty error to the dev when trying to install DevTools.

Thanks, keep 'em coming!

**Comment by OccultScientist** [comment]
Quick question. Is it possible to edit or delete models from Devtools or does this need doing in the code?

**Comment by tabacitu** [comment]
@OccultScientist - it's not possible to edit or delete Models in DevTools, no. We're considering adding a Delete button, but editing... that'll be an inferior experience to your editor, no matter how hard we try. That's why we added the possibility to click the model so it opens in your editor/IDE - that way editing is always one click away.

Let us know what you think about that decision 😉

**Comment by jonathands** [comment]
Just for reference and the people finding this from google: 

you probably forgot to run php artisan backpack:install otherwise you might have to run php artisan backpack:publish-middleware
